---
title           : "The Longitudinal Association Between Early Peer Sexual Harassment and Later Dating Violence"
shorttitle      : "A preregistration of secondary data analysis on PRISE Data"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Aziz-Kaan Dönmez
    affiliation : 1
  - name        : Carolina Lunde
    affiliation : 1
affiliation:
  - id          : 1
    institution : University of Gothenburg
csl: apa7.csl
output: prereg::prereg_pdf
bibliography: prereg_references.bib
---

# Study Information

## Title

The Longitudinal Association Between Early Peer Sexual Harassment and Later Dating Violence

## Description

Peer sexual harassment (PSH), defined here as unwanted sexual attention from peers in the school environment (Mcmaster et al., 2002) is a commonly occurring form of victimisation among adolescents (Ngo et al., 2018; Ståhl & Dennhag, 2021). PSH is associated with adverse outcomes such as internalising problems (Dahlqvist et al., 2016).

Children who report experiencing one type of victimisation are significantly more likely to report being targets of other types of victimisations (Finkelhor et al., 2011). This phenomena has been called polyvictimisation, the experience of multiple different forms of victimisations (Finkelhor et al., 2011). One such association related to PSH that has been found is dating violence, a form of intimate partner violence that occurs in the context of dating relationships (XXX). That is, children who report being victims of PSH also report being victims of dating violence.  

The aim of this paper is therefore to investigate the longitudinal association between SH victimisation and subsequent dating violence victimisation and perpetration. This is done in the context of the revictimisation theory which states that individuals who are victims of one or multiple types of aggressions are more likely to be victims of same or other types of victimisations in the future. Furthermore, we are interested in whether there is a dose-dependent relationship between victimisation and adverse outcomes such as dating violence (perpetration and victimisation). A dose-dependent relationship is defined as the association between sexual harassment and adverse outcomes (dating violence perpetration/victimisation) being stronger for individuals who report being sexual harassment at more timepoints.

## Hypotheses

H1: Higher levels of peer-victimization (sexual harassment) at earlier grades (4, 5, 6, 7 and 7) will predict higher levels of dating-violence victimization at grade 8.

H2: Previous SH victimisation will be associated with subsequent SH victimisation.

H3: There will be a dose-dependent relationship such that greater frequency of SH victimisation will be associated with a higher risk of both TDV and SH victimisation.

H4: The association between SH victimisation and TDV victimisation will be moderated by gender such that the association will be stronger for girls compared to boys.

H5: The path from SH victimisation to TDV victimisation will be mediated through X

# Design Plan

## Study type

**Observational Study**. The study started in 2019 when participants were in grade 4. It is ongoing and the last wave of data collection (4th) were conducted in 2023. The next wave (5th) is planned to be collected in February of 2024, at which point the participants will be in grade 8.

## Study design

The data for this paper will come from the ongoing longitudinal PRISE-project. In short, the PRISE project recruited participants from schools around in Västra Götaland, Sweden. The first wave of data collection was conducted in 2019 and new ones have been collected yearly since then. The project is, as of right now (2023-11-27), in its 4th wave with plans to collect the 5th wave in February 2024. It has adopted a survey methodology where a comprehensive list of variables related to peer-victimization and its correlates are measured through questionnaires. The majority of participants fills out the questionnaire in school with the presence of a research personnel. However, those who are absentee at the time of data-collection, or those students who are not in the recruited schools are given the opportunity to fill out the questionnaire at home.

# Sampling Plan

## Existing data
**Registration following analysis of the data**. As of the date of submission, some of the data used for this paper has been accessed and analyzed. However, the analysis conducted has primarily been psychometric evaluations of the peer sexual harassment scale (PSH-C; one of the main predictor variables in this paper). This has been done for T1 (grade 4), T3 (grade 6) and T4 (grade 7). However, the author AKD has not analysed any associations between the three different time points. Furthermore, psychometric evaluations have been conducted on the outcome variable (Dating Violence) for T4, but no associations between the outcome variable and predictor variables have been conducted prior to date.

## Explanation of existing data

Much of the variables of interest from the existing data has been psychometrically investigated. That is, a confirmatory factor analysis have been ran on the variables. However, no cross-sectional or longitudinal associations between the variables have been investigated. The author conducting the analyses (AKD) have not been involved with data-collection prior to T4.

## Data collection procedures

Schools around the Västra Götaland region in Sweden were contacted and asked to participate in the study. The process of selecting schools was primarily guided by the enrollment patterns of participants in the PRISE study. In instances where participants transitioned to a different school for grade 7, schools were chosen based on the destination schools for the majority of graduating students. This decision was informed by data obtained from the elementary school management office of the regional municipality. Essentially, the selection hinged on a combination of the original schools attended by PRISE participants and, when applicable, the schools to which most students from the graduating schools transitioned, as indicated by information from the regional elementary school management office. A total of 25 schools were contacted, 11 of which agreed to participate. Guardians of students in grade 7 were sent information about the study, and consent forms via post. The schools were then visited, and students whos' guardians had given consent were given information about the study and then asked to participate in the study. Students whos' parents had given consent but were absent from class during the time of data-collection, and students from the PRISE study that did not attend any of the recruited schools, were contacted via post and asked to participate in the study online at home.

## Sample size and rationale

The original PRISE 4-6 study determined sample size using power calculations. From Skoog et al. (2019): "The sample size, N= 1000, is based on conventional calculations (Cohen, 1988), aiming for 80% power, .05 alpha, the ability to detect small effect sizes, and using more than ten predictors (Miles & Shevlin, 2001). The size further accounts for some attrition (10%) that might occur over the study period."

The sample size of the continuation of the project, that is PRISE 7-9, is following the same students and has therefore no power calculations but instead attempted to recruit as many of the participants in PRISE 4-6 as possible. 

# Variables

<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->

## Manipulated variables

```{=html}
<!-- Describe all variables you plan to manipulate and the levels or treatment arms of each variable. This is not applicable to any observational study. For any experimental manipulation, you should give a precise definition of each manipulated variable. This must include a precise description of the levels at which each variable will be set, or a specific definition for each categorical treatment. For example, “loud or quiet,” should instead give either a precise decibel level or a means of recreating each level. 'Presence/absence' or 'positive/negative' is an acceptable description if the variable is precisely described.

Example: We manipulated the percentage of sugar by mass added to brownies. The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane sugar by mass. -->
```
Enter your response here.

## Measured variables

```{=html}
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'

Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being 'not at all', 7 being 'a great deal') and 'How good did the brownie taste' (on a scale of 1-7, 1 being 'very bad', 7 being 'very good'). -->
```
Enter your response here.

## Indices

```{=html}
<!-- If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.

If you are using multiple pieces of data to construct a single variable, how will this occur? Both the data that are included and the formula or weights for each measure must be specified. Standard summary statistics, such as "means" do not require a formula, though more complicated indices require either the exact formula or, if it is an established index in the field, the index must be unambiguously defined. For example, "biodiversity index" is too broad, whereas "Shannon’s biodiversity index" is appropriate.

Example: We will take the mean of the two questions above to create a single measure of 'brownie enjoyment.'  -->
```
Enter your response here.

# Analysis Plan

```{=html}
<!-- You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. -->
```

## Measurement Model Assessment
Analysis 1. Confirmatory factor analyses will be conducted on the listed measures to confirm its factor structure. 
Analysis 2. A longitudinal and gender invariance analysis will be conducted in order to assess whether the factor structure of the measurements holds over time and gender.

## H1 and H2
Analysis 3. A Latent Variable Cross-lagged Panel Model will be used to assess the association between Sexual Harassment in grade 4, 5, 6, 7 and 8,  and dating violence in grade 8. 

## H3
- not sure yet

## H4
Analysis 4. Gender will be added as a moderator to the same model used in in Analysis 3 in order to test whether there are significant differences in strengths of associations between boys and girls

## H5
Analysis 5. A mediation analysis will be conducted to the same model used in analysis 3 where the path from previous SH to current TDV will be mediated through X.

Predictor variables include peer sexual-harassment, measured using the Peer Sexual Harassment - Child Scale [@valik2022]

## Statistical models

```{=html}
<!-- What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions, subgroup analyses, pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan on using any positive controls, negative controls, or manipulation checks you may mention that here. Remember that any test not included here must be noted as an exploratory test in your final article.

This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analyzing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples:

- If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. 
- If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.

Example:  We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index. -->
```
Enter your response here.

## Transformations

```{=html}
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be.

Example: The "Effect of sugar on brownie tastiness" does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), 'sweet' could be dummy coded with 'not sweet' as the reference category. -->
```
Gender will be dummy-coded such that 1 represents Boys and 2 represents Girls.

## Inference criteria

```{=html}
<!-- What criteria will you use to make inferences? Please describe the information youÍll use (e.g. p-values, bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this?

p-values, confidence intervals, and effect sizes are standard means for making an inference, and any level is acceptable, though some criteria must be specified in this or previous fields. Bayesian analyses should specify a Bayes factor or a credible interval. If you are selecting models, then how will you determine the relative quality of each? In regards to multiple comparisons, this is a question with few "wrong" answers. In other words, transparency is more important than any specific method of controlling the false discovery rate or false error rate. One may state an intention to report all tests conducted or one may conduct a specific correction procedure; either strategy is acceptable.

Example: We will use the standard p<.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test adjusts for multiple comparisons. -->
```
## Data exclusion

```{=html}
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? Will you use any awareness check? Any rule for excluding a particular set of data is acceptable. One may describe rules for excluding a participant or for identifying outlier data.

Example: No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the three tastiness indices. Outliers will be included in the analysis. -->
```

## Missing data

```{=html}
<!-- How will you deal with incomplete or missing data? Any relevant explanation is acceptable. As a final reminder, remember that the final analysis must follow the specified plan, and deviations must be either strongly justified or included as a separate, exploratory analysis.

Example: If a subject does not complete any of the three indices of tastiness, that subject will not be included in the analysis. -->
```
Enter your response here.

## Exploratory analyses (optional)

```{=html}
<!-- If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.

Example: We expect that certain demographic traits may be related to taste preferences. Therefore, we will look for relationships between demographic variables (age, gender, income, and marital status) and the primary outcome measures of taste preferences. -->
```
Enter your response here.

# Other

## Other (Optional)

<!-- If there is any additional information that you feel needs to be included in your preregistration, please enter it here. Literature cited, disclosures of any related work such as replications or work that uses the same data, or other context that will be helpful for future readers would be appropriate here. -->

Enter your response here.

# References

## 

{=tex} \vspace{-2pc} \setlength{\parindent}{-0.5in} \setlength{\leftskip}{-1in} \setlength{\parskip}{8pt}

\noindent
